services:
  - type: web
    name: task-manager-api
    runtime: node
    repo: https://github.com/Praveenkg02/Task-manager
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
